### PR TITLE
Update HolographicDisplays to 3.x

### LINKED ISSUE #64: HoloPlots does not work with HolographicDisplays 3.x
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

Upon plot claiming no hologram is being placed above the claim sign.
Previously claimed plots get a hologram after a server restart. 

### To Reproduce

1. upload plotsquared v6.2.2
2. upload holographicdisplays 3.0.0
3. upload protocollib 4.8.0-b538
2. upload holoplots 6.2.1
3. check already claimed plots if they have a hologram
4. claim a new plot and observe that no hologram is being placed

### Expected behaviour

When a new plot is claimed a hologram should be placed above the sign.

### Screenshots / Videos

https://user-images.githubusercontent.com/57076968/147886361-09c6c8da-b50a-4e5b-943d-017532ce06a8.mp4

### Error log (if applicable)

no errors in the log with debug enabled

### Plot Debugpaste

https://athion.net/ISPaster/paste/view/a2b6ec73c9784608b26cb97db1920b68

### HoloPlots Version

6.2.1

### Checklist

- [X] I have included a Plot debugpaste.
- [X] I am using the newest build from https://www.spigotmc.org/resources/4880/ and the issue still persists.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by NotMyFault**
Fixes #64

I did some testing to ensure the main functionality works still:

https://user-images.githubusercontent.com/13383509/227168201-125aa1f8-1702-4080-ba05-9d24b7fd94e2.mp4

### CODE REVIEW

**Comment by Tsoccerguy3** [comment]
Pull is not working 100 % https://github.com/IntellectualSites/HoloPlots/issues/128
Tested with 1.19.4 See Picture and link to new HoloDisplay for 1.19.4

**Comment by NotMyFault** [comment]
> Pull is not working 100 % https://github.com/IntellectualSites/HoloPlots/issues/128

See Pierre's comments. Fetching the player's head doesn't put a goat in place.

**Comment by NotMyFault** [comment]
I'd appreciate a review, friendly ping @IntellectualSites/plotsquared-team :)

**Comment by NotMyFault** [comment]
Assuming lazy consensus after a month without negative feedback.

**Pull request merged**
